stages:
  - build-and-push

build-and-push:
  image: docker:27
  stage: build-and-push
  services:
    - name: docker:dind
      command: [
        "--registry-mirror=http://gitlab.prodcontest.ru:5015",
        "--registry-mirror=https://dockerhub.timeweb.cloud",
        "--tls=false"
      ]
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_VERIFY: "1"
    REGISTRY: $CI_REGISTRY
    IMAGE_NAME: "$CI_PROJECT_PATH"
    TAG: $CI_COMMIT_REF_NAME
  before_script:
    - until docker info; do sleep 1; done
  script:
    - echo "$CI_REGISTRY_PASSWORD" |
      docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t ${REGISTRY}/${IMAGE_NAME}:${TAG} .
    - docker push ${REGISTRY}/${IMAGE_NAME}:${TAG}
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - changes:
        - "**/*"
      when: on_success
    - changes:
        - .env
        - compose.yml
        - dev-compose.yml
        - pg-compose.yml
        - README.md
        - .gitignore
      when: never
    - when: never