// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Business is the predicate function for business builders.
type Business func(*sql.Selector)

// CoinProgram is the predicate function for coinprogram builders.
type CoinProgram func(*sql.Selector)

// CoinProgramParticipant is the predicate function for coinprogramparticipant builders.
type CoinProgramParticipant func(*sql.Selector)

// Coupon is the predicate function for coupon builders.
type Coupon func(*sql.Selector)

// Reward is the predicate function for reward builders.
type Reward func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
