// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"loyalit/internal/adapters/repository/postgres/ent/business"
	"loyalit/internal/adapters/repository/postgres/ent/coinprogram"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BusinessCreate is the builder for creating a Business entity.
type BusinessCreate struct {
	config
	mutation *BusinessMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (bc *BusinessCreate) SetCreatedAt(t time.Time) *BusinessCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BusinessCreate) SetNillableCreatedAt(t *time.Time) *BusinessCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetName sets the "name" field.
func (bc *BusinessCreate) SetName(s string) *BusinessCreate {
	bc.mutation.SetName(s)
	return bc
}

// SetEmail sets the "email" field.
func (bc *BusinessCreate) SetEmail(s string) *BusinessCreate {
	bc.mutation.SetEmail(s)
	return bc
}

// SetPassword sets the "password" field.
func (bc *BusinessCreate) SetPassword(s string) *BusinessCreate {
	bc.mutation.SetPassword(s)
	return bc
}

// SetDescription sets the "description" field.
func (bc *BusinessCreate) SetDescription(s string) *BusinessCreate {
	bc.mutation.SetDescription(s)
	return bc
}

// SetID sets the "id" field.
func (bc *BusinessCreate) SetID(u uuid.UUID) *BusinessCreate {
	bc.mutation.SetID(u)
	return bc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bc *BusinessCreate) SetNillableID(u *uuid.UUID) *BusinessCreate {
	if u != nil {
		bc.SetID(*u)
	}
	return bc
}

// SetCoinProgramID sets the "coin_program" edge to the CoinProgram entity by ID.
func (bc *BusinessCreate) SetCoinProgramID(id uuid.UUID) *BusinessCreate {
	bc.mutation.SetCoinProgramID(id)
	return bc
}

// SetNillableCoinProgramID sets the "coin_program" edge to the CoinProgram entity by ID if the given value is not nil.
func (bc *BusinessCreate) SetNillableCoinProgramID(id *uuid.UUID) *BusinessCreate {
	if id != nil {
		bc = bc.SetCoinProgramID(*id)
	}
	return bc
}

// SetCoinProgram sets the "coin_program" edge to the CoinProgram entity.
func (bc *BusinessCreate) SetCoinProgram(c *CoinProgram) *BusinessCreate {
	return bc.SetCoinProgramID(c.ID)
}

// Mutation returns the BusinessMutation object of the builder.
func (bc *BusinessCreate) Mutation() *BusinessMutation {
	return bc.mutation
}

// Save creates the Business in the database.
func (bc *BusinessCreate) Save(ctx context.Context) (*Business, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BusinessCreate) SaveX(ctx context.Context) *Business {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BusinessCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BusinessCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BusinessCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := business.DefaultCreatedAt
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.ID(); !ok {
		v := business.DefaultID()
		bc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BusinessCreate) check() error {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Business.created_at"`)}
	}
	if _, ok := bc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Business.name"`)}
	}
	if v, ok := bc.mutation.Name(); ok {
		if err := business.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Business.name": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Business.email"`)}
	}
	if v, ok := bc.mutation.Email(); ok {
		if err := business.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Business.email": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Business.password"`)}
	}
	if v, ok := bc.mutation.Password(); ok {
		if err := business.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Business.password": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Business.description"`)}
	}
	if v, ok := bc.mutation.Description(); ok {
		if err := business.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Business.description": %w`, err)}
		}
	}
	return nil
}

func (bc *BusinessCreate) sqlSave(ctx context.Context) (*Business, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BusinessCreate) createSpec() (*Business, *sqlgraph.CreateSpec) {
	var (
		_node = &Business{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(business.Table, sqlgraph.NewFieldSpec(business.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = bc.conflict
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(business.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.Name(); ok {
		_spec.SetField(business.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := bc.mutation.Email(); ok {
		_spec.SetField(business.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := bc.mutation.Password(); ok {
		_spec.SetField(business.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := bc.mutation.Description(); ok {
		_spec.SetField(business.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := bc.mutation.CoinProgramIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   business.CoinProgramTable,
			Columns: []string{business.CoinProgramColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coinprogram.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Business.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BusinessUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (bc *BusinessCreate) OnConflict(opts ...sql.ConflictOption) *BusinessUpsertOne {
	bc.conflict = opts
	return &BusinessUpsertOne{
		create: bc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Business.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bc *BusinessCreate) OnConflictColumns(columns ...string) *BusinessUpsertOne {
	bc.conflict = append(bc.conflict, sql.ConflictColumns(columns...))
	return &BusinessUpsertOne{
		create: bc,
	}
}

type (
	// BusinessUpsertOne is the builder for "upsert"-ing
	//  one Business node.
	BusinessUpsertOne struct {
		create *BusinessCreate
	}

	// BusinessUpsert is the "OnConflict" setter.
	BusinessUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *BusinessUpsert) SetName(v string) *BusinessUpsert {
	u.Set(business.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessUpsert) UpdateName() *BusinessUpsert {
	u.SetExcluded(business.FieldName)
	return u
}

// SetEmail sets the "email" field.
func (u *BusinessUpsert) SetEmail(v string) *BusinessUpsert {
	u.Set(business.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *BusinessUpsert) UpdateEmail() *BusinessUpsert {
	u.SetExcluded(business.FieldEmail)
	return u
}

// SetPassword sets the "password" field.
func (u *BusinessUpsert) SetPassword(v string) *BusinessUpsert {
	u.Set(business.FieldPassword, v)
	return u
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *BusinessUpsert) UpdatePassword() *BusinessUpsert {
	u.SetExcluded(business.FieldPassword)
	return u
}

// SetDescription sets the "description" field.
func (u *BusinessUpsert) SetDescription(v string) *BusinessUpsert {
	u.Set(business.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BusinessUpsert) UpdateDescription() *BusinessUpsert {
	u.SetExcluded(business.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Business.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(business.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BusinessUpsertOne) UpdateNewValues() *BusinessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(business.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(business.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Business.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BusinessUpsertOne) Ignore() *BusinessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BusinessUpsertOne) DoNothing() *BusinessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BusinessCreate.OnConflict
// documentation for more info.
func (u *BusinessUpsertOne) Update(set func(*BusinessUpsert)) *BusinessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BusinessUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *BusinessUpsertOne) SetName(v string) *BusinessUpsertOne {
	return u.Update(func(s *BusinessUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessUpsertOne) UpdateName() *BusinessUpsertOne {
	return u.Update(func(s *BusinessUpsert) {
		s.UpdateName()
	})
}

// SetEmail sets the "email" field.
func (u *BusinessUpsertOne) SetEmail(v string) *BusinessUpsertOne {
	return u.Update(func(s *BusinessUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *BusinessUpsertOne) UpdateEmail() *BusinessUpsertOne {
	return u.Update(func(s *BusinessUpsert) {
		s.UpdateEmail()
	})
}

// SetPassword sets the "password" field.
func (u *BusinessUpsertOne) SetPassword(v string) *BusinessUpsertOne {
	return u.Update(func(s *BusinessUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *BusinessUpsertOne) UpdatePassword() *BusinessUpsertOne {
	return u.Update(func(s *BusinessUpsert) {
		s.UpdatePassword()
	})
}

// SetDescription sets the "description" field.
func (u *BusinessUpsertOne) SetDescription(v string) *BusinessUpsertOne {
	return u.Update(func(s *BusinessUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BusinessUpsertOne) UpdateDescription() *BusinessUpsertOne {
	return u.Update(func(s *BusinessUpsert) {
		s.UpdateDescription()
	})
}

// Exec executes the query.
func (u *BusinessUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BusinessCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BusinessUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BusinessUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BusinessUpsertOne.ID is not supported by MySQL driver. Use BusinessUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BusinessUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BusinessCreateBulk is the builder for creating many Business entities in bulk.
type BusinessCreateBulk struct {
	config
	err      error
	builders []*BusinessCreate
	conflict []sql.ConflictOption
}

// Save creates the Business entities in the database.
func (bcb *BusinessCreateBulk) Save(ctx context.Context) ([]*Business, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Business, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BusinessMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = bcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BusinessCreateBulk) SaveX(ctx context.Context) []*Business {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BusinessCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BusinessCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Business.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BusinessUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (bcb *BusinessCreateBulk) OnConflict(opts ...sql.ConflictOption) *BusinessUpsertBulk {
	bcb.conflict = opts
	return &BusinessUpsertBulk{
		create: bcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Business.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bcb *BusinessCreateBulk) OnConflictColumns(columns ...string) *BusinessUpsertBulk {
	bcb.conflict = append(bcb.conflict, sql.ConflictColumns(columns...))
	return &BusinessUpsertBulk{
		create: bcb,
	}
}

// BusinessUpsertBulk is the builder for "upsert"-ing
// a bulk of Business nodes.
type BusinessUpsertBulk struct {
	create *BusinessCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Business.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(business.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BusinessUpsertBulk) UpdateNewValues() *BusinessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(business.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(business.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Business.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BusinessUpsertBulk) Ignore() *BusinessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BusinessUpsertBulk) DoNothing() *BusinessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BusinessCreateBulk.OnConflict
// documentation for more info.
func (u *BusinessUpsertBulk) Update(set func(*BusinessUpsert)) *BusinessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BusinessUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *BusinessUpsertBulk) SetName(v string) *BusinessUpsertBulk {
	return u.Update(func(s *BusinessUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BusinessUpsertBulk) UpdateName() *BusinessUpsertBulk {
	return u.Update(func(s *BusinessUpsert) {
		s.UpdateName()
	})
}

// SetEmail sets the "email" field.
func (u *BusinessUpsertBulk) SetEmail(v string) *BusinessUpsertBulk {
	return u.Update(func(s *BusinessUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *BusinessUpsertBulk) UpdateEmail() *BusinessUpsertBulk {
	return u.Update(func(s *BusinessUpsert) {
		s.UpdateEmail()
	})
}

// SetPassword sets the "password" field.
func (u *BusinessUpsertBulk) SetPassword(v string) *BusinessUpsertBulk {
	return u.Update(func(s *BusinessUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *BusinessUpsertBulk) UpdatePassword() *BusinessUpsertBulk {
	return u.Update(func(s *BusinessUpsert) {
		s.UpdatePassword()
	})
}

// SetDescription sets the "description" field.
func (u *BusinessUpsertBulk) SetDescription(v string) *BusinessUpsertBulk {
	return u.Update(func(s *BusinessUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BusinessUpsertBulk) UpdateDescription() *BusinessUpsertBulk {
	return u.Update(func(s *BusinessUpsert) {
		s.UpdateDescription()
	})
}

// Exec executes the query.
func (u *BusinessUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BusinessCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BusinessCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BusinessUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
