// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"loyalit/internal/adapters/repository/postgres/ent/coinprogram"
	"loyalit/internal/adapters/repository/postgres/ent/coinprogramparticipant"
	"loyalit/internal/adapters/repository/postgres/ent/predicate"
	"loyalit/internal/adapters/repository/postgres/ent/user"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CoinProgramParticipantQuery is the builder for querying CoinProgramParticipant entities.
type CoinProgramParticipantQuery struct {
	config
	ctx             *QueryContext
	order           []coinprogramparticipant.OrderOption
	inters          []Interceptor
	predicates      []predicate.CoinProgramParticipant
	withCoinProgram *CoinProgramQuery
	withUser        *UserQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CoinProgramParticipantQuery builder.
func (cppq *CoinProgramParticipantQuery) Where(ps ...predicate.CoinProgramParticipant) *CoinProgramParticipantQuery {
	cppq.predicates = append(cppq.predicates, ps...)
	return cppq
}

// Limit the number of records to be returned by this query.
func (cppq *CoinProgramParticipantQuery) Limit(limit int) *CoinProgramParticipantQuery {
	cppq.ctx.Limit = &limit
	return cppq
}

// Offset to start from.
func (cppq *CoinProgramParticipantQuery) Offset(offset int) *CoinProgramParticipantQuery {
	cppq.ctx.Offset = &offset
	return cppq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cppq *CoinProgramParticipantQuery) Unique(unique bool) *CoinProgramParticipantQuery {
	cppq.ctx.Unique = &unique
	return cppq
}

// Order specifies how the records should be ordered.
func (cppq *CoinProgramParticipantQuery) Order(o ...coinprogramparticipant.OrderOption) *CoinProgramParticipantQuery {
	cppq.order = append(cppq.order, o...)
	return cppq
}

// QueryCoinProgram chains the current query on the "coin_program" edge.
func (cppq *CoinProgramParticipantQuery) QueryCoinProgram() *CoinProgramQuery {
	query := (&CoinProgramClient{config: cppq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cppq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(coinprogramparticipant.Table, coinprogramparticipant.FieldID, selector),
			sqlgraph.To(coinprogram.Table, coinprogram.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, coinprogramparticipant.CoinProgramTable, coinprogramparticipant.CoinProgramColumn),
		)
		fromU = sqlgraph.SetNeighbors(cppq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (cppq *CoinProgramParticipantQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: cppq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cppq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(coinprogramparticipant.Table, coinprogramparticipant.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, coinprogramparticipant.UserTable, coinprogramparticipant.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(cppq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CoinProgramParticipant entity from the query.
// Returns a *NotFoundError when no CoinProgramParticipant was found.
func (cppq *CoinProgramParticipantQuery) First(ctx context.Context) (*CoinProgramParticipant, error) {
	nodes, err := cppq.Limit(1).All(setContextOp(ctx, cppq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{coinprogramparticipant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cppq *CoinProgramParticipantQuery) FirstX(ctx context.Context) *CoinProgramParticipant {
	node, err := cppq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CoinProgramParticipant ID from the query.
// Returns a *NotFoundError when no CoinProgramParticipant ID was found.
func (cppq *CoinProgramParticipantQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cppq.Limit(1).IDs(setContextOp(ctx, cppq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{coinprogramparticipant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cppq *CoinProgramParticipantQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cppq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CoinProgramParticipant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CoinProgramParticipant entity is found.
// Returns a *NotFoundError when no CoinProgramParticipant entities are found.
func (cppq *CoinProgramParticipantQuery) Only(ctx context.Context) (*CoinProgramParticipant, error) {
	nodes, err := cppq.Limit(2).All(setContextOp(ctx, cppq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{coinprogramparticipant.Label}
	default:
		return nil, &NotSingularError{coinprogramparticipant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cppq *CoinProgramParticipantQuery) OnlyX(ctx context.Context) *CoinProgramParticipant {
	node, err := cppq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CoinProgramParticipant ID in the query.
// Returns a *NotSingularError when more than one CoinProgramParticipant ID is found.
// Returns a *NotFoundError when no entities are found.
func (cppq *CoinProgramParticipantQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cppq.Limit(2).IDs(setContextOp(ctx, cppq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{coinprogramparticipant.Label}
	default:
		err = &NotSingularError{coinprogramparticipant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cppq *CoinProgramParticipantQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cppq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CoinProgramParticipants.
func (cppq *CoinProgramParticipantQuery) All(ctx context.Context) ([]*CoinProgramParticipant, error) {
	ctx = setContextOp(ctx, cppq.ctx, ent.OpQueryAll)
	if err := cppq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CoinProgramParticipant, *CoinProgramParticipantQuery]()
	return withInterceptors[[]*CoinProgramParticipant](ctx, cppq, qr, cppq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cppq *CoinProgramParticipantQuery) AllX(ctx context.Context) []*CoinProgramParticipant {
	nodes, err := cppq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CoinProgramParticipant IDs.
func (cppq *CoinProgramParticipantQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cppq.ctx.Unique == nil && cppq.path != nil {
		cppq.Unique(true)
	}
	ctx = setContextOp(ctx, cppq.ctx, ent.OpQueryIDs)
	if err = cppq.Select(coinprogramparticipant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cppq *CoinProgramParticipantQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cppq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cppq *CoinProgramParticipantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cppq.ctx, ent.OpQueryCount)
	if err := cppq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cppq, querierCount[*CoinProgramParticipantQuery](), cppq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cppq *CoinProgramParticipantQuery) CountX(ctx context.Context) int {
	count, err := cppq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cppq *CoinProgramParticipantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cppq.ctx, ent.OpQueryExist)
	switch _, err := cppq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cppq *CoinProgramParticipantQuery) ExistX(ctx context.Context) bool {
	exist, err := cppq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CoinProgramParticipantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cppq *CoinProgramParticipantQuery) Clone() *CoinProgramParticipantQuery {
	if cppq == nil {
		return nil
	}
	return &CoinProgramParticipantQuery{
		config:          cppq.config,
		ctx:             cppq.ctx.Clone(),
		order:           append([]coinprogramparticipant.OrderOption{}, cppq.order...),
		inters:          append([]Interceptor{}, cppq.inters...),
		predicates:      append([]predicate.CoinProgramParticipant{}, cppq.predicates...),
		withCoinProgram: cppq.withCoinProgram.Clone(),
		withUser:        cppq.withUser.Clone(),
		// clone intermediate query.
		sql:  cppq.sql.Clone(),
		path: cppq.path,
	}
}

// WithCoinProgram tells the query-builder to eager-load the nodes that are connected to
// the "coin_program" edge. The optional arguments are used to configure the query builder of the edge.
func (cppq *CoinProgramParticipantQuery) WithCoinProgram(opts ...func(*CoinProgramQuery)) *CoinProgramParticipantQuery {
	query := (&CoinProgramClient{config: cppq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cppq.withCoinProgram = query
	return cppq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (cppq *CoinProgramParticipantQuery) WithUser(opts ...func(*UserQuery)) *CoinProgramParticipantQuery {
	query := (&UserClient{config: cppq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cppq.withUser = query
	return cppq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CoinProgramParticipant.Query().
//		GroupBy(coinprogramparticipant.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cppq *CoinProgramParticipantQuery) GroupBy(field string, fields ...string) *CoinProgramParticipantGroupBy {
	cppq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CoinProgramParticipantGroupBy{build: cppq}
	grbuild.flds = &cppq.ctx.Fields
	grbuild.label = coinprogramparticipant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CoinProgramParticipant.Query().
//		Select(coinprogramparticipant.FieldCreatedAt).
//		Scan(ctx, &v)
func (cppq *CoinProgramParticipantQuery) Select(fields ...string) *CoinProgramParticipantSelect {
	cppq.ctx.Fields = append(cppq.ctx.Fields, fields...)
	sbuild := &CoinProgramParticipantSelect{CoinProgramParticipantQuery: cppq}
	sbuild.label = coinprogramparticipant.Label
	sbuild.flds, sbuild.scan = &cppq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CoinProgramParticipantSelect configured with the given aggregations.
func (cppq *CoinProgramParticipantQuery) Aggregate(fns ...AggregateFunc) *CoinProgramParticipantSelect {
	return cppq.Select().Aggregate(fns...)
}

func (cppq *CoinProgramParticipantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cppq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cppq); err != nil {
				return err
			}
		}
	}
	for _, f := range cppq.ctx.Fields {
		if !coinprogramparticipant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cppq.path != nil {
		prev, err := cppq.path(ctx)
		if err != nil {
			return err
		}
		cppq.sql = prev
	}
	return nil
}

func (cppq *CoinProgramParticipantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CoinProgramParticipant, error) {
	var (
		nodes       = []*CoinProgramParticipant{}
		withFKs     = cppq.withFKs
		_spec       = cppq.querySpec()
		loadedTypes = [2]bool{
			cppq.withCoinProgram != nil,
			cppq.withUser != nil,
		}
	)
	if cppq.withCoinProgram != nil || cppq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, coinprogramparticipant.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CoinProgramParticipant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CoinProgramParticipant{config: cppq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cppq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cppq.withCoinProgram; query != nil {
		if err := cppq.loadCoinProgram(ctx, query, nodes, nil,
			func(n *CoinProgramParticipant, e *CoinProgram) { n.Edges.CoinProgram = e }); err != nil {
			return nil, err
		}
	}
	if query := cppq.withUser; query != nil {
		if err := cppq.loadUser(ctx, query, nodes, nil,
			func(n *CoinProgramParticipant, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cppq *CoinProgramParticipantQuery) loadCoinProgram(ctx context.Context, query *CoinProgramQuery, nodes []*CoinProgramParticipant, init func(*CoinProgramParticipant), assign func(*CoinProgramParticipant, *CoinProgram)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CoinProgramParticipant)
	for i := range nodes {
		if nodes[i].coin_program_participant_coin_program == nil {
			continue
		}
		fk := *nodes[i].coin_program_participant_coin_program
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(coinprogram.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "coin_program_participant_coin_program" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cppq *CoinProgramParticipantQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CoinProgramParticipant, init func(*CoinProgramParticipant), assign func(*CoinProgramParticipant, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CoinProgramParticipant)
	for i := range nodes {
		if nodes[i].user_coin_programs == nil {
			continue
		}
		fk := *nodes[i].user_coin_programs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_coin_programs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cppq *CoinProgramParticipantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cppq.querySpec()
	_spec.Node.Columns = cppq.ctx.Fields
	if len(cppq.ctx.Fields) > 0 {
		_spec.Unique = cppq.ctx.Unique != nil && *cppq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cppq.driver, _spec)
}

func (cppq *CoinProgramParticipantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(coinprogramparticipant.Table, coinprogramparticipant.Columns, sqlgraph.NewFieldSpec(coinprogramparticipant.FieldID, field.TypeUUID))
	_spec.From = cppq.sql
	if unique := cppq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cppq.path != nil {
		_spec.Unique = true
	}
	if fields := cppq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coinprogramparticipant.FieldID)
		for i := range fields {
			if fields[i] != coinprogramparticipant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cppq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cppq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cppq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cppq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cppq *CoinProgramParticipantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cppq.driver.Dialect())
	t1 := builder.Table(coinprogramparticipant.Table)
	columns := cppq.ctx.Fields
	if len(columns) == 0 {
		columns = coinprogramparticipant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cppq.sql != nil {
		selector = cppq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cppq.ctx.Unique != nil && *cppq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cppq.predicates {
		p(selector)
	}
	for _, p := range cppq.order {
		p(selector)
	}
	if offset := cppq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cppq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CoinProgramParticipantGroupBy is the group-by builder for CoinProgramParticipant entities.
type CoinProgramParticipantGroupBy struct {
	selector
	build *CoinProgramParticipantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cppgb *CoinProgramParticipantGroupBy) Aggregate(fns ...AggregateFunc) *CoinProgramParticipantGroupBy {
	cppgb.fns = append(cppgb.fns, fns...)
	return cppgb
}

// Scan applies the selector query and scans the result into the given value.
func (cppgb *CoinProgramParticipantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cppgb.build.ctx, ent.OpQueryGroupBy)
	if err := cppgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CoinProgramParticipantQuery, *CoinProgramParticipantGroupBy](ctx, cppgb.build, cppgb, cppgb.build.inters, v)
}

func (cppgb *CoinProgramParticipantGroupBy) sqlScan(ctx context.Context, root *CoinProgramParticipantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cppgb.fns))
	for _, fn := range cppgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cppgb.flds)+len(cppgb.fns))
		for _, f := range *cppgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cppgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cppgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CoinProgramParticipantSelect is the builder for selecting fields of CoinProgramParticipant entities.
type CoinProgramParticipantSelect struct {
	*CoinProgramParticipantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cpps *CoinProgramParticipantSelect) Aggregate(fns ...AggregateFunc) *CoinProgramParticipantSelect {
	cpps.fns = append(cpps.fns, fns...)
	return cpps
}

// Scan applies the selector query and scans the result into the given value.
func (cpps *CoinProgramParticipantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cpps.ctx, ent.OpQuerySelect)
	if err := cpps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CoinProgramParticipantQuery, *CoinProgramParticipantSelect](ctx, cpps.CoinProgramParticipantQuery, cpps, cpps.inters, v)
}

func (cpps *CoinProgramParticipantSelect) sqlScan(ctx context.Context, root *CoinProgramParticipantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cpps.fns))
	for _, fn := range cpps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cpps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cpps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
