// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"loyalit/internal/adapters/repository/postgres/ent/coinprogram"
	"loyalit/internal/adapters/repository/postgres/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CoinProgramDelete is the builder for deleting a CoinProgram entity.
type CoinProgramDelete struct {
	config
	hooks    []Hook
	mutation *CoinProgramMutation
}

// Where appends a list predicates to the CoinProgramDelete builder.
func (cpd *CoinProgramDelete) Where(ps ...predicate.CoinProgram) *CoinProgramDelete {
	cpd.mutation.Where(ps...)
	return cpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cpd *CoinProgramDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cpd.sqlExec, cpd.mutation, cpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cpd *CoinProgramDelete) ExecX(ctx context.Context) int {
	n, err := cpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cpd *CoinProgramDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(coinprogram.Table, sqlgraph.NewFieldSpec(coinprogram.FieldID, field.TypeUUID))
	if ps := cpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cpd.mutation.done = true
	return affected, err
}

// CoinProgramDeleteOne is the builder for deleting a single CoinProgram entity.
type CoinProgramDeleteOne struct {
	cpd *CoinProgramDelete
}

// Where appends a list predicates to the CoinProgramDelete builder.
func (cpdo *CoinProgramDeleteOne) Where(ps ...predicate.CoinProgram) *CoinProgramDeleteOne {
	cpdo.cpd.mutation.Where(ps...)
	return cpdo
}

// Exec executes the deletion query.
func (cpdo *CoinProgramDeleteOne) Exec(ctx context.Context) error {
	n, err := cpdo.cpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{coinprogram.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cpdo *CoinProgramDeleteOne) ExecX(ctx context.Context) {
	if err := cpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
