// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"loyalit/internal/adapters/repository/postgres/ent/coinprogram"
	"loyalit/internal/adapters/repository/postgres/ent/coupon"
	"loyalit/internal/adapters/repository/postgres/ent/reward"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RewardCreate is the builder for creating a Reward entity.
type RewardCreate struct {
	config
	mutation *RewardMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (rc *RewardCreate) SetCreatedAt(t time.Time) *RewardCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RewardCreate) SetNillableCreatedAt(t *time.Time) *RewardCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetName sets the "name" field.
func (rc *RewardCreate) SetName(s string) *RewardCreate {
	rc.mutation.SetName(s)
	return rc
}

// SetDescription sets the "description" field.
func (rc *RewardCreate) SetDescription(s string) *RewardCreate {
	rc.mutation.SetDescription(s)
	return rc
}

// SetCost sets the "cost" field.
func (rc *RewardCreate) SetCost(u uint) *RewardCreate {
	rc.mutation.SetCost(u)
	return rc
}

// SetImageURL sets the "image_url" field.
func (rc *RewardCreate) SetImageURL(s string) *RewardCreate {
	rc.mutation.SetImageURL(s)
	return rc
}

// SetID sets the "id" field.
func (rc *RewardCreate) SetID(u uuid.UUID) *RewardCreate {
	rc.mutation.SetID(u)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *RewardCreate) SetNillableID(u *uuid.UUID) *RewardCreate {
	if u != nil {
		rc.SetID(*u)
	}
	return rc
}

// SetCoinProgramID sets the "coin_program" edge to the CoinProgram entity by ID.
func (rc *RewardCreate) SetCoinProgramID(id uuid.UUID) *RewardCreate {
	rc.mutation.SetCoinProgramID(id)
	return rc
}

// SetNillableCoinProgramID sets the "coin_program" edge to the CoinProgram entity by ID if the given value is not nil.
func (rc *RewardCreate) SetNillableCoinProgramID(id *uuid.UUID) *RewardCreate {
	if id != nil {
		rc = rc.SetCoinProgramID(*id)
	}
	return rc
}

// SetCoinProgram sets the "coin_program" edge to the CoinProgram entity.
func (rc *RewardCreate) SetCoinProgram(c *CoinProgram) *RewardCreate {
	return rc.SetCoinProgramID(c.ID)
}

// AddRewardIDs adds the "rewards" edge to the Coupon entity by IDs.
func (rc *RewardCreate) AddRewardIDs(ids ...uuid.UUID) *RewardCreate {
	rc.mutation.AddRewardIDs(ids...)
	return rc
}

// AddRewards adds the "rewards" edges to the Coupon entity.
func (rc *RewardCreate) AddRewards(c ...*Coupon) *RewardCreate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return rc.AddRewardIDs(ids...)
}

// Mutation returns the RewardMutation object of the builder.
func (rc *RewardCreate) Mutation() *RewardMutation {
	return rc.mutation
}

// Save creates the Reward in the database.
func (rc *RewardCreate) Save(ctx context.Context) (*Reward, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RewardCreate) SaveX(ctx context.Context) *Reward {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RewardCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RewardCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RewardCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := reward.DefaultCreatedAt
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.ID(); !ok {
		v := reward.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RewardCreate) check() error {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Reward.created_at"`)}
	}
	if _, ok := rc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Reward.name"`)}
	}
	if v, ok := rc.mutation.Name(); ok {
		if err := reward.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Reward.name": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Reward.description"`)}
	}
	if _, ok := rc.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "Reward.cost"`)}
	}
	if v, ok := rc.mutation.Cost(); ok {
		if err := reward.CostValidator(v); err != nil {
			return &ValidationError{Name: "cost", err: fmt.Errorf(`ent: validator failed for field "Reward.cost": %w`, err)}
		}
	}
	if _, ok := rc.mutation.ImageURL(); !ok {
		return &ValidationError{Name: "image_url", err: errors.New(`ent: missing required field "Reward.image_url"`)}
	}
	if v, ok := rc.mutation.ImageURL(); ok {
		if err := reward.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Reward.image_url": %w`, err)}
		}
	}
	return nil
}

func (rc *RewardCreate) sqlSave(ctx context.Context) (*Reward, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RewardCreate) createSpec() (*Reward, *sqlgraph.CreateSpec) {
	var (
		_node = &Reward{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(reward.Table, sqlgraph.NewFieldSpec(reward.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = rc.conflict
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(reward.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.Name(); ok {
		_spec.SetField(reward.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := rc.mutation.Description(); ok {
		_spec.SetField(reward.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := rc.mutation.Cost(); ok {
		_spec.SetField(reward.FieldCost, field.TypeUint, value)
		_node.Cost = value
	}
	if value, ok := rc.mutation.ImageURL(); ok {
		_spec.SetField(reward.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if nodes := rc.mutation.CoinProgramIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reward.CoinProgramTable,
			Columns: []string{reward.CoinProgramColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coinprogram.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.coin_program_rewards = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.RewardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   reward.RewardsTable,
			Columns: []string{reward.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coupon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Reward.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RewardUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (rc *RewardCreate) OnConflict(opts ...sql.ConflictOption) *RewardUpsertOne {
	rc.conflict = opts
	return &RewardUpsertOne{
		create: rc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Reward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rc *RewardCreate) OnConflictColumns(columns ...string) *RewardUpsertOne {
	rc.conflict = append(rc.conflict, sql.ConflictColumns(columns...))
	return &RewardUpsertOne{
		create: rc,
	}
}

type (
	// RewardUpsertOne is the builder for "upsert"-ing
	//  one Reward node.
	RewardUpsertOne struct {
		create *RewardCreate
	}

	// RewardUpsert is the "OnConflict" setter.
	RewardUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *RewardUpsert) SetName(v string) *RewardUpsert {
	u.Set(reward.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RewardUpsert) UpdateName() *RewardUpsert {
	u.SetExcluded(reward.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *RewardUpsert) SetDescription(v string) *RewardUpsert {
	u.Set(reward.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RewardUpsert) UpdateDescription() *RewardUpsert {
	u.SetExcluded(reward.FieldDescription)
	return u
}

// SetCost sets the "cost" field.
func (u *RewardUpsert) SetCost(v uint) *RewardUpsert {
	u.Set(reward.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *RewardUpsert) UpdateCost() *RewardUpsert {
	u.SetExcluded(reward.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *RewardUpsert) AddCost(v uint) *RewardUpsert {
	u.Add(reward.FieldCost, v)
	return u
}

// SetImageURL sets the "image_url" field.
func (u *RewardUpsert) SetImageURL(v string) *RewardUpsert {
	u.Set(reward.FieldImageURL, v)
	return u
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *RewardUpsert) UpdateImageURL() *RewardUpsert {
	u.SetExcluded(reward.FieldImageURL)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Reward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(reward.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RewardUpsertOne) UpdateNewValues() *RewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(reward.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(reward.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Reward.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RewardUpsertOne) Ignore() *RewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RewardUpsertOne) DoNothing() *RewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RewardCreate.OnConflict
// documentation for more info.
func (u *RewardUpsertOne) Update(set func(*RewardUpsert)) *RewardUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RewardUpsertOne) SetName(v string) *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RewardUpsertOne) UpdateName() *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *RewardUpsertOne) SetDescription(v string) *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RewardUpsertOne) UpdateDescription() *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.UpdateDescription()
	})
}

// SetCost sets the "cost" field.
func (u *RewardUpsertOne) SetCost(v uint) *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *RewardUpsertOne) AddCost(v uint) *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *RewardUpsertOne) UpdateCost() *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.UpdateCost()
	})
}

// SetImageURL sets the "image_url" field.
func (u *RewardUpsertOne) SetImageURL(v string) *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.SetImageURL(v)
	})
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *RewardUpsertOne) UpdateImageURL() *RewardUpsertOne {
	return u.Update(func(s *RewardUpsert) {
		s.UpdateImageURL()
	})
}

// Exec executes the query.
func (u *RewardUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RewardCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RewardUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RewardUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RewardUpsertOne.ID is not supported by MySQL driver. Use RewardUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RewardUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RewardCreateBulk is the builder for creating many Reward entities in bulk.
type RewardCreateBulk struct {
	config
	err      error
	builders []*RewardCreate
	conflict []sql.ConflictOption
}

// Save creates the Reward entities in the database.
func (rcb *RewardCreateBulk) Save(ctx context.Context) ([]*Reward, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Reward, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RewardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RewardCreateBulk) SaveX(ctx context.Context) []*Reward {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RewardCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RewardCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Reward.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RewardUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (rcb *RewardCreateBulk) OnConflict(opts ...sql.ConflictOption) *RewardUpsertBulk {
	rcb.conflict = opts
	return &RewardUpsertBulk{
		create: rcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Reward.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rcb *RewardCreateBulk) OnConflictColumns(columns ...string) *RewardUpsertBulk {
	rcb.conflict = append(rcb.conflict, sql.ConflictColumns(columns...))
	return &RewardUpsertBulk{
		create: rcb,
	}
}

// RewardUpsertBulk is the builder for "upsert"-ing
// a bulk of Reward nodes.
type RewardUpsertBulk struct {
	create *RewardCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Reward.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(reward.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RewardUpsertBulk) UpdateNewValues() *RewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(reward.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(reward.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Reward.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RewardUpsertBulk) Ignore() *RewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RewardUpsertBulk) DoNothing() *RewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RewardCreateBulk.OnConflict
// documentation for more info.
func (u *RewardUpsertBulk) Update(set func(*RewardUpsert)) *RewardUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RewardUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RewardUpsertBulk) SetName(v string) *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RewardUpsertBulk) UpdateName() *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *RewardUpsertBulk) SetDescription(v string) *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RewardUpsertBulk) UpdateDescription() *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.UpdateDescription()
	})
}

// SetCost sets the "cost" field.
func (u *RewardUpsertBulk) SetCost(v uint) *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *RewardUpsertBulk) AddCost(v uint) *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *RewardUpsertBulk) UpdateCost() *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.UpdateCost()
	})
}

// SetImageURL sets the "image_url" field.
func (u *RewardUpsertBulk) SetImageURL(v string) *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.SetImageURL(v)
	})
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *RewardUpsertBulk) UpdateImageURL() *RewardUpsertBulk {
	return u.Update(func(s *RewardUpsert) {
		s.UpdateImageURL()
	})
}

// Exec executes the query.
func (u *RewardUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RewardCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RewardCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RewardUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
