// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"loyalit/internal/adapters/repository/postgres/ent/coinprogram"
	"loyalit/internal/adapters/repository/postgres/ent/reward"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Reward is the model entity for the Reward schema.
type Reward struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Cost holds the value of the "cost" field.
	Cost uint `json:"cost,omitempty"`
	// ImageURL holds the value of the "image_url" field.
	ImageURL string `json:"image_url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RewardQuery when eager-loading is set.
	Edges                RewardEdges `json:"edges"`
	coin_program_rewards *uuid.UUID
	selectValues         sql.SelectValues
}

// RewardEdges holds the relations/edges for other nodes in the graph.
type RewardEdges struct {
	// CoinProgram holds the value of the coin_program edge.
	CoinProgram *CoinProgram `json:"coin_program,omitempty"`
	// Rewards holds the value of the rewards edge.
	Rewards []*Coupon `json:"rewards,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CoinProgramOrErr returns the CoinProgram value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RewardEdges) CoinProgramOrErr() (*CoinProgram, error) {
	if e.CoinProgram != nil {
		return e.CoinProgram, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: coinprogram.Label}
	}
	return nil, &NotLoadedError{edge: "coin_program"}
}

// RewardsOrErr returns the Rewards value or an error if the edge
// was not loaded in eager-loading.
func (e RewardEdges) RewardsOrErr() ([]*Coupon, error) {
	if e.loadedTypes[1] {
		return e.Rewards, nil
	}
	return nil, &NotLoadedError{edge: "rewards"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Reward) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reward.FieldCost:
			values[i] = new(sql.NullInt64)
		case reward.FieldName, reward.FieldDescription, reward.FieldImageURL:
			values[i] = new(sql.NullString)
		case reward.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case reward.FieldID:
			values[i] = new(uuid.UUID)
		case reward.ForeignKeys[0]: // coin_program_rewards
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Reward fields.
func (r *Reward) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reward.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				r.ID = *value
			}
		case reward.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		case reward.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				r.Name = value.String
			}
		case reward.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				r.Description = value.String
			}
		case reward.FieldCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				r.Cost = uint(value.Int64)
			}
		case reward.FieldImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_url", values[i])
			} else if value.Valid {
				r.ImageURL = value.String
			}
		case reward.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field coin_program_rewards", values[i])
			} else if value.Valid {
				r.coin_program_rewards = new(uuid.UUID)
				*r.coin_program_rewards = *value.S.(*uuid.UUID)
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Reward.
// This includes values selected through modifiers, order, etc.
func (r *Reward) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryCoinProgram queries the "coin_program" edge of the Reward entity.
func (r *Reward) QueryCoinProgram() *CoinProgramQuery {
	return NewRewardClient(r.config).QueryCoinProgram(r)
}

// QueryRewards queries the "rewards" edge of the Reward entity.
func (r *Reward) QueryRewards() *CouponQuery {
	return NewRewardClient(r.config).QueryRewards(r)
}

// Update returns a builder for updating this Reward.
// Note that you need to call Reward.Unwrap() before calling this method if this Reward
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Reward) Update() *RewardUpdateOne {
	return NewRewardClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Reward entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Reward) Unwrap() *Reward {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Reward is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Reward) String() string {
	var builder strings.Builder
	builder.WriteString("Reward(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(r.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(r.Description)
	builder.WriteString(", ")
	builder.WriteString("cost=")
	builder.WriteString(fmt.Sprintf("%v", r.Cost))
	builder.WriteString(", ")
	builder.WriteString("image_url=")
	builder.WriteString(r.ImageURL)
	builder.WriteByte(')')
	return builder.String()
}

// Rewards is a parsable slice of Reward.
type Rewards []*Reward
